# Generated by Django 2.2.10 on 2021-09-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата старта')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_q', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('type_q', models.CharField(choices=[('text_input', 'Ввод текста'), ('simple_choice', 'выбор одного ответа'), ('multi_choice', 'мультивыбор')], max_length=20, verbose_name='Тип ответа')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_id', to='poll_api.Poll', verbose_name='Название опросника')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default='0')),
                ('answer', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='poll_api.Question')),
            ],
        ),
    ]
